// src/components/Resume.svelte
<script>
	let link;
</script>

<div class="resume-container">
	<h1 class="header-text">Not Currently Job Hunting</h1>
	<a class="link-text" href="mailto: ibergalec@icloud.com"><h4>Please request here</h4></a>
</div>

<style>
	.resume-container {
	}

	.header-text {
		color: #65946a;
	}

	.link-text {
		color: #6f1d1b;
	}
</style>

// src/components/resume/resume.component.jsx
import React, { useState } from 'react';

import resume from './alecibergresume.pdf';

import { Document, Page, pdfjs } from 'react-pdf';

pdfjs.GlobalWorkerOptions.workerSrc = `//cdnjs.cloudflare.com/ajax/libs/pdf.js/${pdfjs.version}/pdf.worker.js`;

const Resume = () => {
  const [numPages, setNumPages] = useState(null);
  const [pageNumber] = useState(1);

  const onDocumentLoadSuccess = ({ numPages }) => {
    setNumPages(numPages);
  };

  return (
    <div>
      {/* <Document file={resume} onLoadSuccess={onDocumentLoadSuccess}>
        <Page pageNumber={pageNumber} />
      </Document> */}
      Not currently job hunting, resume available upon{' '}
      <a
        href="mailto: ibergalec@icloud.com"
        style={{ color: '#65946a', fontWeight: 'bold' }}
      >
        request.
      </a>
    </div>
  );
};

export default Resume;
