// src/routes/Skills/+page.svelte
<script>
	import Skill from '$lib/components/Skill.svelte';

	const skills = [
		{ name: 'TypeScript', image: '/images/typescript.png' },
		{ name: 'React', image: '/images/react.png' },
		{ name: 'Svelte', image: '/images/svelte.png' },
		{ name: 'JavaScript', image: '/images/js.png' },
		{ name: 'Redux', image: '/images/Redux.png' },
		{ name: 'Git', image: '/images/gitbash.png' },
		{ name: 'CI/CD', image: '/images/gitlab-ci.png' },
		{ name: 'Jest', image: '/images/jest.png' },
		{ name: 'GoLang', image: '/images/golang.png' },
		{ name: 'Node', image: '/images/node.png' }
	];
</script>

<div class="skills-container">
	{#each skills as skill}
		<div class="skill">
			<Skill {skill} />
		</div>
	{/each}
</div>

<style>
	.skills-container {
		display: grid;
		overflow: scroll;
		gap: 5px;
		grid-template-columns: auto auto auto;
	}

	.skill {
	}
</style>

// src/components/skills-component/skills-component.jsx
import gitlab from './gitlab-ci.png';
import jest from './jest.png';
import node from './node.png';
import react from './React-icon.svg.png';
import redux from './Redux.png';
import typescript from './typescript.png';
import javascript from './js.png';
import gitbash from './gitbash.png';
import svelte from './svelte.png';
import golang from './golang.png';

import './skills.styles.css';

import Skill from '../skill-component/skill.component';
import Grid from '@mui/material/Grid';

const Skills = () => {
  const skills = [
    { name: 'TypeScript', image: typescript },
    { name: 'ReactJS', image: react },
    { name: 'JavaScript', image: javascript },
    { name: 'Svelte', image: svelte },
    { name: 'NodeJS', image: node },
    { name: 'Go', image: golang },
    { name: 'Jest', image: jest },
    { name: 'Redux', image: redux },
    { name: 'CI/CD', image: gitlab },
    { name: 'GitBash', image: gitbash },
  ];
  return (
    <Grid
      container
      sx={{ height: '20vh' }}
      m={1}
      p={1}
      spacing={{ xs: 2, md: 1 }}
      columns={4}
    >
      {skills.map((skill) => {
        return (
          <Grid item xs={4} md={2} lg={1}>
            <Skill skill={skill}></Skill>
          </Grid>
        );
      })}
    </Grid>
  );
};

export default Skills;
