// src/lib/components/Skills.svelte
<script>
  import Skill from "$lib/components/Skill.svelte";

  let innerWidth;

  const skills = [
    { name: "TypeScript", image: "/images/typescript.png" },
    { name: "Svelte", image: "/images/svelte.png" },
    { name: "GoLang", image: "/images/golang.png" },
    { name: "JavaScript", image: "/images/js.png" },
    { name: "React", image: "/images/react.png" },
    { name: "Redux", image: "/images/Redux.png" },
    { name: "Git", image: "/images/gitbash.png" },
    { name: "CI/CD", image: "/images/gitlab-ci.png" },
    { name: "Jest", image: "/images/jest.png" },
    { name: "Node", image: "/images/node.png" },
  ];
</script>

<svelte:window bind:innerWidth />

<div class="skills-holder">
  <h1>Skills</h1>
  <div class={innerWidth < 600 ? "skills-container-small" : "skills-container"}>
    {#each skills as skill}
      <div class="skill">
        <Skill {skill} />
      </div>
    {/each}
  </div>
  <br />
  <br />
</div>

<style>
  .skills-holder {
    width: 100vw;
    margin: auto;
    text-align: center;
    border-bottom: 3px solid rgba(118, 171, 174, 0.5);
  }
  .skills-container {
    display: grid;
    overflow: scroll;
    align-items: center;
    justify-content: center;
    width: 80vw;
    /* gap: 5px; */
    grid-template-columns: auto auto auto auto;
  }

  .skills-container-small {
    display: grid;
    overflow: scroll;
    gap: 5px;
    grid-template-columns: auto auto;
  }

  h1 {
    font-size: 48px;
    color: #76abae;
  }
</style>

// src/components/skills-component/skills-component.jsx
import gitlab from './gitlab-ci.png';
import jest from './jest.png';
import node from './node.png';
import react from './React-icon.svg.png';
import redux from './Redux.png';
import typescript from './typescript.png';
import javascript from './js.png';
import gitbash from './gitbash.png';
import svelte from './svelte.png';
import golang from './golang.png';

import './skills.styles.css';

import Skill from '../skill-component/skill.component';
import Grid from '@mui/material/Grid';

const Skills = ({ isMobile }) => {
  const skills = [
    { name: 'TypeScript', image: typescript },
    { name: 'ReactJS', image: react },
    { name: 'JavaScript', image: javascript },
    { name: 'Svelte', image: svelte },
    { name: 'NodeJS', image: node },
    { name: 'Go', image: golang },
    { name: 'Jest', image: jest },
    { name: 'Redux', image: redux },
    { name: 'CI/CD', image: gitlab },
    { name: 'GitBash', image: gitbash },
  ];
  return (
    <Grid
      container
      sx={{ height: '20vh' }}
      m={1}
      p={1}
      spacing={{ xs: 2, md: 1 }}
      columns={4}
      style={{
        margin: isMobile ? '35px' : '',
        padding: isMobile ? '20px' : '',
      }}
    >
      {skills.map((skill) => {
        return (
          <Grid key={skill} item xs={4} md={2} lg={1}>
            <Skill key={skill} skill={skill}></Skill>
          </Grid>
        );
      })}
    </Grid>
  );
};

export default Skills;
